development:
  adapter: postgresql
  encoding: unicode
  database: dz_ac_dev
  pool: 5
  username: wtm_local
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: dz_ac_test
  pool: 5
  username: wtm_local
  password:
